package docsgen

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/EvilFreelancer/coddy-agent/internal/docs"
)

// The documentation layer of coddy.dev. Every page of the map has a stable
// address there, coddy.dev/docs/<slug>, and nothing is duplicated: GitHub
// Pages serves 404.html for every address that is not a file, so one script
// on that page reads the path and sends the visitor to the page on GitHub
// (the fragment survives); coddy.dev/docs/<slug>.md goes to the raw Markdown
// the same way. llms.txt and llms-full.txt at the site root point straight
// at the raw Markdown on the main branch. The binary, the schema and the
// bundled skill print the stable addresses, so a page can move in the
// repository without changing what users were told. A Cloudflare redirect
// rule in front of the site turns the same mapping into a real 301 without
// touching any of this (see docs/contributing/documentation.md).
const (
	SiteBase   = "https://coddy.dev/docs/"
	GitHubBlob = "https://github.com/coddy-project/coddy-agent/blob/main/"
	GitHubRaw  = "https://raw.githubusercontent.com/coddy-project/coddy-agent/main/"

	// SiteRedirectScript is the file the site's 404.html loads.
	SiteRedirectScript = "docs-redirect.js"
)

// SiteSlug is the address of a nav page under coddy.dev/docs/: the path
// without its extension; a page outside docs/ (../CONTRIBUTING.md) is known
// by its file name.
func SiteSlug(navPath string) string {
	p := strings.TrimSuffix(filepath.ToSlash(navPath), ".md")
	if strings.HasPrefix(p, "../") {
		return path.Base(p)
	}
	return p
}

// SiteRedirectURL is the human address of a nav page on the site.
func SiteRedirectURL(navPath string) string { return SiteBase + SiteSlug(navPath) }

// RawPageURL is the Markdown of a nav page as agents fetch it.
func RawPageURL(navPath string) string { return GitHubRaw + RepoPath(navPath) }

// rootPages lists the map's pages that live outside docs/, keyed by slug, so
// the interceptor knows that /docs/CONTRIBUTING is CONTRIBUTING.md at the
// repository root and not docs/CONTRIBUTING.md.
func rootPages(nav *Nav) map[string]string {
	out := map[string]string{}
	for _, p := range nav.Pages() {
		if strings.HasPrefix(filepath.ToSlash(p.Path), "../") {
			out[SiteSlug(p.Path)] = RepoPath(p.Path)
		}
	}
	return out
}

// RenderSite renders the files of the documentation layer, keyed by their
// path relative to the site checkout: the interceptor script. The llms files
// are added by the caller.
func RenderSite(nav *Nav) map[string]string {
	return map[string]string{SiteRedirectScript: redirectScript(rootPages(nav), Translations)}
}

// redirectScript is the interceptor 404.html loads. coddyDocsTarget is a pure
// function of the path, the fragment and the anchors of a translation, so it
// can be tested in a browser without navigating; the trailing call performs
// the redirect when the page was reached under /docs or /<lang>/docs.
//
// A translated page answers to the anchors of its English source in the
// binary, and the links Coddy prints carry those; GitHub knows only the
// anchors of the translated headings. For an address of a translation with a
// fragment the script fetches docs-anchors-<lang>.json, the map from one to
// the other, and only then redirects.
func redirectScript(root map[string]string, langs []string) string {
	rootJSON, _ := json.Marshal(root)
	langsJSON, _ := json.Marshal(langs)
	return fmt.Sprintf(`// Generated by make site-docs in coddy-project/coddy-agent from docs/nav.yaml.
// GitHub Pages serves 404.html for every address that is not a file; this
// script turns /docs/<path> into the page on GitHub and /docs/<path>.md into
// its raw Markdown, keeping the fragment, and /<lang>/docs/<path> into the
// translation under docs/<lang>/ (LANGS). Root pages of the repository that
// the map includes are listed in ROOT; they are not translated.
(function () {
  var BLOB = %q;
  var RAW = %q;
  var ROOT = %s;
  var LANGS = %s;

  function coddyDocsTarget(pathname, hash, anchors) {
    var m = /^\/(?:([a-z]{2})\/)?docs(?:\/(.*))?$/.exec(pathname || "");
    if (!m) return null;
    var lang = m[1] && LANGS.indexOf(m[1]) >= 0 ? m[1] : "";
    if (m[1] && !lang) return null;
    var p = (m[2] || "").replace(/\/+$/, "");
    hash = hash || "";
    var dir = "docs/" + (lang ? lang + "/" : "");
    if (p === "") return BLOB + dir + "README.md" + hash;
    var raw = /\.md$/.test(p);
    var slug = raw ? p.slice(0, -3) : p;
    if (lang && hash && anchors && anchors[slug]) {
      var local = anchors[slug][decodeURIComponent(hash.slice(1)).toLowerCase()];
      if (local) hash = "#" + local;
    }
    var file = ROOT[slug] || (dir + slug + ".md");
    return (raw ? RAW : BLOB) + file + hash;
  }

  if (typeof window !== "undefined") {
    window.coddyDocsTarget = coddyDocsTarget;
    var go = function (anchors) {
      var target = coddyDocsTarget(window.location.pathname, window.location.hash, anchors);
      if (target) window.location.replace(target);
    };
    var t = /^\/([a-z]{2})\/docs\//.exec(window.location.pathname);
    if (t && LANGS.indexOf(t[1]) >= 0 && window.location.hash && typeof fetch === "function") {
      fetch("/docs-anchors-" + t[1] + ".json").then(function (r) { return r.json(); }).then(go, function () { go(null); });
    } else {
      go(null);
    }
  }
})();
`, GitHubBlob, GitHubRaw, rootJSON, langsJSON)
}

// RenderSiteLang renders the documentation layer of every translation next to
// the English one: the interceptor, and for each language
// docs-anchors-<lang>.json (shared anchor to the translated heading's own,
// per page), <lang>/llms.txt and <lang>/llms-full.txt. The English llms files
// are added by the caller.
func RenderSiteLang(root string, nav *Nav, trs map[string]*TranslatedNav) (map[string]string, error) {
	files := RenderSite(nav)
	for _, lang := range Translations {
		tr := trs[lang]
		if tr == nil {
			continue
		}
		lib, err := docs.LoadLang(os.DirFS(filepath.Join(root, "docs")), "dev", lang)
		if err != nil {
			return nil, err
		}
		anchors := map[string]map[string]string{}
		for _, p := range lib.Pages() {
			if p.Lang != lang {
				continue
			}
			for _, h := range p.Headings {
				if h.Local != h.Anchor {
					if anchors[p.Slug] == nil {
						anchors[p.Slug] = map[string]string{}
					}
					anchors[p.Slug][h.Anchor] = h.Local
				}
			}
		}
		data, err := json.Marshal(anchors)
		if err != nil {
			return nil, err
		}
		files["docs-anchors-"+lang+".json"] = string(data) + "\n"
		hub, _ := os.ReadFile(filepath.Join(root, TranslationDir(lang)+"README.md"))
		files[lang+"/llms.txt"] = RenderLLMSIndexLang(nav, tr, lang, string(hub), DefaultRawBase)
		full, err := RenderLLMSFullLang(nav, tr, lang, root, DefaultRawBase)
		if err != nil {
			return nil, err
		}
		files[lang+"/llms-full.txt"] = full
	}
	return files, nil
}

// SiteStale compares the rendered site files with a checkout.
func SiteStale(siteDir string, files map[string]string) []Problem {
	var out []Problem
	for rel, content := range files {
		data, err := os.ReadFile(filepath.Join(siteDir, rel))
		if err != nil || strings.TrimRight(string(data), "\n") != strings.TrimRight(content, "\n") {
			out = append(out, Problem{"site:" + rel, "stale or missing on the site, run make site-docs"})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].File < out[j].File })
	return out
}

// WriteSite stores the site files under siteDir.
func WriteSite(siteDir string, files map[string]string) error {
	for rel, content := range files {
		p := filepath.Join(siteDir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}
